import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const compile=source=>'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText).toString('base64');
const coreUrl=compile(fs.readFileSync('src/lib/scanner.ts','utf8'));
const core=await import(coreUrl);
const rangesUrl=compile(fs.readFileSync('src/lib/ranges.ts','utf8').replace("'./scanner'",JSON.stringify(coreUrl)));
const ranges=await import(rangesUrl);
const snapshot=await import(compile(fs.readFileSync('src/lib/snapshot.ts','utf8').replace("'./scanner'",JSON.stringify(coreUrl)).replace("'./ranges'",JSON.stringify(rangesUrl))));
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
near(core.rangeDrawdown(100,99.64),.36);
assert.equal(core.rangeDrawdown(0,1),null);
assert.equal(core.rangeDrawdown(100,101),null);
assert.equal(core.rangeDrawdown(null,99),null);
assert.equal(core.rangeDrawdown(Infinity,1),null);
for(const [value,expected] of [[0,'Exceptional RS'],[39.999,'Exceptional RS'],[40,'Clear RS'],[69.999,'Clear RS'],[70,'Moderate RS'],[99.999,'Moderate RS'],[100,'Market-like'],[125,'Market-like'],[125.001,'Laggard']])assert.equal(core.classify(value),expected);
const stock={...core.IMPORTED.stocks[0],drawdown:.36,low:99.64,last:100.8,previousClose:101};
const m=core.metrics(stock,{drawdown:1.2});near(m.capture,30);near(m.advantage,.84);near(m.recovery,(100.8/99.64-1)*100);assert.ok(m.absolute<0);assert.equal(m.band,'Exceptional RS');
assert.equal(core.metrics(stock,{drawdown:0}).capture,null);
assert.equal(core.metrics({...stock,drawdown:null},{drawdown:1.2}).capture,null);
assert.equal(core.benchmarkFor('COST','Retail trade'),'ES');assert.equal(core.benchmarkFor('AMZN','Retail trade'),'NQ');
assert.equal(new Date(ranges.easternTime('2026-09-28',4)).toISOString(),'2026-09-28T08:00:00.000Z');
assert.equal(new Date(ranges.easternTime('2026-01-12',4)).toISOString(),'2026-01-12T09:00:00.000Z');
assert.equal(new Date(ranges.easternTime('2026-03-08',4)).toISOString(),'2026-03-08T08:00:00.000Z');
assert.equal(new Date(ranges.easternTime('2026-11-01',4)).toISOString(),'2026-11-01T09:00:00.000Z');
const w=ranges.windows('2026-09-28');assert.equal(new Date(w.futuresStart).toISOString(),'2026-09-27T22:00:00.000Z');assert.equal(new Date(w.end).toISOString(),'2026-09-28T13:20:00.000Z');
const t=w.equityStart;
const bars=[{t:t-60000,h:500,l:1,c:100,v:9999},{t,h:101,l:100,c:100.5,v:1000},{t:t+60000,h:102,l:99,c:101,v:2000},{t:w.end,h:900,l:1,c:500,v:9999}];
const a=ranges.aggregate(bars,w.equityStart,w.end);assert.equal(a.high,102);assert.equal(a.low,99);assert.equal(a.volume,3000);assert.equal(a.last,101);near(a.drawdown,100*(1-99/102));
assert.equal(ranges.aggregate(bars,w.end+1,w.end+60000),null);
const reversed=ranges.aggregate([{t,h:100,l:90,c:95,v:100},{t:t+60000,h:110,l:99,c:110,v:100}],t,t+120000);near(reversed.drawdown,100*(1-90/110)); // range, not chronological maximum drawdown
assert.equal(core.marketSession(new Date('2026-09-28T08:00Z')).active,true);assert.equal(core.marketSession(new Date('2026-09-28T13:30Z')).active,false);assert.equal(core.marketSession(new Date('2026-09-27T12:00Z')).active,false);
const sorted=core.IMPORTED.stocks.map(r=>({ticker:r.ticker,...core.metrics(r,core.IMPORTED.benchmarks.find(b=>b.id===r.benchmark))})).sort((a,b)=>a.capture-b.capture||a.ticker.localeCompare(b.ticker));assert.deepEqual(sorted.slice(0,3).map(r=>r.ticker),['AAPL','CSCO','TSLA']);
const candidateRows=Array.from({length:30},(_,i)=>({ticker:`T${String(i).padStart(2,'0')}`,capture:30-i}));
candidateRows.push({ticker:'NO_RANGE',capture:null},{ticker:'INVALID',capture:Infinity});
const top=core.topRelativeStrength(candidateRows);
assert.equal(top.length,25);assert.deepEqual(top.slice(0,2).map(r=>[r.ticker,r.rsRank]),[['T29',1],['T28',2]]);
assert.equal(top.at(-1).ticker,'T05');assert.equal(candidateRows[0].ticker,'T00');
assert.deepEqual(core.topRelativeStrength([{ticker:'B',capture:10},{ticker:'A',capture:10}],2).map(r=>r.ticker),['A','B']);
assert.equal(new Date(ranges.windows('2026-01-12').end).toISOString(),'2026-01-12T14:20:00.000Z');
assert.equal(snapshot.readSnapshot(core.IMPORTED).status,'imported');
const briefingPacket=structuredClone(core.IMPORTED);briefingPacket.briefing={indices:[{title:'Overnight tape',body:'Benchmark range held below the prior close.',source:'TradingView',url:'https://www.tradingview.com/chart/',publishedAt:'2026-09-28T12:00:00Z'}],bonds:[],macro:[],earnings:[],news:[]};assert.equal(snapshot.readSnapshot(briefingPacket).briefing.indices[0].source,'TradingView');
assert.throws(()=>snapshot.readSnapshot({...briefingPacket,briefing:{...briefingPacket.briefing,indices:[{...briefingPacket.briefing.indices[0],url:'javascript:alert(1)'}]}}),/direct HTTPS/);
const packet={...structuredClone(core.IMPORTED),status:'frozen',universeComplete:true,cutoffAt:'2026-09-28T13:20:00Z',fetchedAt:'2026-09-28T13:20:15Z'};
for(const row of [...packet.stocks,...packet.sectors,...packet.benchmarks])Object.assign(row,{high:100,low:99,last:99.5,drawdown:77,volume:1000,asOf:'2026-09-28T13:19:00Z',highTime:'2026-09-28T12:00:00Z',lowTime:'2026-09-28T13:00:00Z'});
const parsed=snapshot.readSnapshot(packet);assert.equal(parsed.status,'frozen');near(parsed.stocks[0].drawdown,1);near(parsed.benchmarks[0].drawdown,1);
assert.throws(()=>snapshot.readSnapshot({...packet,cutoffAt:'2026-09-28T13:30:00Z'}),/cutoff/);
assert.throws(()=>snapshot.readSnapshot({...packet,fetchedAt:'2026-09-28T13:19:59Z'}),/collection/);
const contaminated=structuredClone(packet);contaminated.stocks[0].asOf='2026-09-28T13:20:00Z';assert.throws(()=>snapshot.readSnapshot(contaminated),/outside/);
const incomplete=structuredClone(packet);delete incomplete.stocks[0].highTime;assert.equal(snapshot.readSnapshot(incomplete).stocks[0].drawdown,null);assert.equal(snapshot.readSnapshot(incomplete).status,'partial');
const illiquid=structuredClone(packet);illiquid.stocks[0].volume=0;assert.equal(snapshot.readSnapshot(illiquid).stocks[0].drawdown,null);
console.log('PASS: fixed 06:20 Pacific cutoff, snapshot validation, drawdowns, thresholds, missing data, benchmark mapping, recovery, DST, session isolation, range ordering, and top-25 ranking.');
