import { useEffect, useMemo, useState } from 'react';
import { Check, ChevronDown, Copy, Play, RotateCcw, SlidersHorizontal, X } from 'lucide-react';

type Motion = { headingMs:number; headingY:number; paperMs:number; paperY:number; paperDelay:number; jumpMs:number; jumpDelay:number; jumpY:number; cardMs:number; cardY:number; cardStagger:number; resilienceMs:number; resilienceStagger:number; sourcesMs:number };
type Text = { titleDesktop:number; titleMobile:number; section:number; card:number; body:number; interface:number; market:number };
type Palette = { background:string; marketStrip:string; surface:string; secondary:string; foreground:string; header:string; secondaryText:string; border:string; divider:string; up:string; down:string };
type GradientType = 'linear'|'radial'|'angular';
type Gradient = { enabled:boolean; type:GradientType; start:string; end:string; angle:number; spread:number };
type GradientSurfaces = { background:Gradient; marketStrip:Gradient; surface:Gradient; secondary:Gradient };
type Colors = { light:Palette; dark:Palette; gradients:{light:GradientSurfaces;dark:GradientSurfaces}; resilience:{exceptional:string;clear:string;moderate:string;market:string;laggard:string} };
type Settings = { motion:Motion; text:Text; colors:Colors };

const defaults:Settings={
  motion:{headingMs:980,headingY:12,paperMs:930,paperY:8,paperDelay:120,jumpMs:1020,jumpDelay:900,jumpY:4,cardMs:650,cardY:12,cardStagger:70,resilienceMs:880,resilienceStagger:105,sourcesMs:480},
  text:{titleDesktop:43,titleMobile:35,section:24,card:16,body:14,interface:16,market:34},
  colors:{light:{background:'#f4f1eb',marketStrip:'#fbfaf8',surface:'#fbfaf8',secondary:'#e8e5df',foreground:'#000000',header:'#000000',secondaryText:'#555555',border:'#d7d3cc',divider:'#000000',up:'#27824d',down:'#c63e3e'},dark:{background:'#25282b',marketStrip:'#292d31',surface:'#303438',secondary:'#3a3e42',foreground:'#e7e8e9',header:'#e7e8e9',secondaryText:'#aeb2b6',border:'#4a4f54',divider:'#e7e8e9',up:'#62c982',down:'#f07878'},gradients:{light:{background:{enabled:false,type:'linear',start:'#f4f1eb',end:'#fbfaf8',angle:135,spread:100},marketStrip:{enabled:false,type:'linear',start:'#fbfaf8',end:'#e8e5df',angle:135,spread:100},surface:{enabled:false,type:'linear',start:'#fbfaf8',end:'#e8e5df',angle:135,spread:100},secondary:{enabled:false,type:'linear',start:'#e8e5df',end:'#fbfaf8',angle:135,spread:100}},dark:{background:{enabled:false,type:'linear',start:'#25282b',end:'#303438',angle:135,spread:100},marketStrip:{enabled:false,type:'linear',start:'#292d31',end:'#3a3e42',angle:135,spread:100},surface:{enabled:false,type:'linear',start:'#303438',end:'#3a3e42',angle:135,spread:100},secondary:{enabled:false,type:'linear',start:'#3a3e42',end:'#303438',angle:135,spread:100}}},resilience:{exceptional:'#c3f86b',clear:'#89b861',moderate:'#708c5d',market:'#bea16e',laggard:'#c5807a'}}
};
const STORE='warren-design-labs-v1';
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,Number.isFinite(v)?v:min));
function loadSettings():Settings { try { const raw=localStorage.getItem(STORE);if(!raw)return defaults;const p=JSON.parse(raw);const merge=(base:Record<string,unknown>,src:unknown):Record<string,unknown>=>Object.fromEntries(Object.entries(base).map(([k,v])=>[k,v&&typeof v==='object'&&!Array.isArray(v)?merge(v as Record<string,unknown>,(src as Record<string,unknown>|undefined)?.[k]):(src as Record<string,unknown>|undefined)?.[k]??v]));return merge(defaults as unknown as Record<string,unknown>,p) as unknown as Settings; } catch { return defaults; } }
const hex=(value:string)=>/^#[\da-f]{6}$/i.test(value);
const gradientCss=(value:Gradient)=>value.type==='radial'?`radial-gradient(circle ${value.spread}% at center, ${value.start} 0%, ${value.end} 100%)`:value.type==='angular'?`conic-gradient(from ${value.angle}deg, ${value.start}, ${value.end}, ${value.start})`:`linear-gradient(${value.angle}deg, ${value.start} 0%, ${value.end} 100%)`;

function Range({label,value,defaultValue,min,max,step=1,unit='',onChange}:{label:string;value:number;defaultValue:number;min:number;max:number;step?:number;unit?:string;onChange:(n:number)=>void}) { return <div className="lab-control"><div className="lab-range"><span>{label}<b>{value}{unit}</b></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><input aria-label={`${label} value`} className="lab-number" type="number" min={min} max={max} step={step} value={value} onChange={e=>onChange(clamp(Number(e.target.value),min,max))}/></div><button type="button" className="lab-reset" aria-label={`Reset ${label} to default`} title={`Reset ${label} to default`} onClick={()=>onChange(defaultValue)}><RotateCcw size={13}/></button></div>; }
function Color({label,value,defaultValue,onChange}:{label:string;value:string;defaultValue:string;onChange:(s:string)=>void}) { const[draft,setDraft]=useState(value);useEffect(()=>setDraft(value),[value]);const commit=()=>{if(hex(draft))onChange(draft.toLowerCase());else setDraft(value);};return <div className="lab-color"><span>{label}</span><input aria-label={`${label} color picker`} type="color" value={hex(value)?value:'#000000'} onChange={e=>{setDraft(e.target.value);onChange(e.target.value);}}/><input aria-label={`${label} hex value`} className="lab-hex" type="text" value={draft} maxLength={7} spellCheck={false} placeholder="#RRGGBB" onChange={e=>{const next=e.target.value;setDraft(next);if(hex(next))onChange(next.toLowerCase());}} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/><button type="button" className="lab-reset" aria-label={`Reset ${label} to default`} title={`Reset ${label} to default`} onClick={()=>{setDraft(defaultValue);onChange(defaultValue);}}><RotateCcw size={13}/></button></div>; }
function GradientControl({label,value,defaultValue,onChange}:{label:string;value:Gradient;defaultValue:Gradient;onChange:(patch:Partial<Gradient>)=>void}) { return <section className="lab-gradient-editor"><div className="lab-gradient-head"><strong>{label}</strong><button type="button" className="lab-reset" aria-label={`Reset ${label} gradient to default`} title={`Reset ${label} gradient to default`} onClick={()=>onChange(defaultValue)}><RotateCcw size={13}/></button></div><label className="lab-gradient-toggle"><input type="checkbox" checked={value.enabled} onChange={e=>onChange({enabled:e.target.checked})}/><span>Use gradient background</span><small>{value.enabled?'On':'Solid color'}</small></label>{value.enabled&&<><div className="lab-select-row"><label htmlFor={`gradient-${label.replace(/\W+/g,'-').toLowerCase()}`}>Gradient style</label><select id={`gradient-${label.replace(/\W+/g,'-').toLowerCase()}`} aria-label={`${label} gradient style`} value={value.type} onChange={e=>onChange({type:e.target.value as GradientType})}><option value="linear">Linear</option><option value="radial">Radial</option><option value="angular">Angular</option></select><button type="button" className="lab-reset" aria-label={`Reset ${label} gradient style to default`} title="Reset gradient style to default" onClick={()=>onChange({type:defaultValue.type})}><RotateCcw size={13}/></button></div>{value.type==='radial'?<Range label={`${label} radial spread`} value={value.spread} defaultValue={defaultValue.spread} min={40} max={180} unit="%" onChange={n=>onChange({spread:n})}/>:<Range label={`${label} angle`} value={value.angle} defaultValue={defaultValue.angle} min={0} max={360} unit="°" onChange={n=>onChange({angle:n})}/>}<Color label={`${label} gradient start`} value={value.start} defaultValue={defaultValue.start} onChange={start=>onChange({start})}/><Color label={`${label} gradient end`} value={value.end} defaultValue={defaultValue.end} onChange={end=>onChange({end})}/><div className="lab-gradient-preview" style={{backgroundImage:gradientCss(value)}} aria-label={`${label} gradient preview`} /></>}</section>; }
function Group({title,children,defaultOpen=false}:{title:string;children:React.ReactNode;defaultOpen?:boolean}) { return <details className="lab-group" open={defaultOpen}><summary>{title}<ChevronDown size={15}/></summary><div className="lab-group-content">{children}</div></details>; }

export default function DesignLabs(){
  const [settings,setSettings]=useState<Settings>(defaults);const [open,setOpen]=useState(false);const [tab,setTab]=useState<'motion'|'text'|'color'>('motion');const [colorMode,setColorMode]=useState<'light'|'dark'>(()=>document.documentElement.dataset.theme==='light'?'light':'dark');const [reduced,setReduced]=useState(false);const [copied,setCopied]=useState(false);
  useEffect(()=>setSettings(loadSettings()),[]);
  useEffect(()=>{const root=document.documentElement;const sync=()=>setColorMode(root.dataset.theme==='light'?'light':'dark');sync();const observer=new MutationObserver(sync);observer.observe(root,{attributes:true,attributeFilter:['data-theme']});return()=>observer.disconnect();},[]);
  useEffect(()=>{try{localStorage.setItem(STORE,JSON.stringify(settings));}catch{}},[settings]);
  useEffect(()=>{
    const root=document.documentElement;root.dataset.devLab='true';root.dataset.devReducedMotion=String(reduced);
    const vars:Record<string,string>={
      '--lab-heading-duration':`${settings.motion.headingMs}ms`,'--lab-heading-distance':`${settings.motion.headingY}px`,'--lab-paper-duration':`${settings.motion.paperMs}ms`,'--lab-paper-distance':`${settings.motion.paperY}px`,'--lab-paper-delay':`${settings.motion.paperDelay}ms`,'--lab-jump-duration':`${settings.motion.jumpMs}ms`,'--lab-jump-delay':`${settings.motion.jumpDelay}ms`,'--lab-jump-distance':`${settings.motion.jumpY}px`,'--lab-card-duration':`${settings.motion.cardMs}ms`,'--lab-card-distance':`${settings.motion.cardY}px`,'--lab-card-stagger':`${settings.motion.cardStagger}ms`,'--lab-resilience-duration':`${settings.motion.resilienceMs}ms`,'--lab-resilience-stagger':`${settings.motion.resilienceStagger}ms`,'--lab-sources-duration':`${settings.motion.sourcesMs}ms`,
      '--lab-sources-opacity-duration':`${Math.round(settings.motion.sourcesMs*.7)}ms`,'--lab-title-desktop':`${settings.text.titleDesktop}px`,'--lab-title-mobile':`${settings.text.titleMobile}px`,'--lab-section-size':`${settings.text.section}px`,'--lab-card-title-size':`${settings.text.card}px`,'--lab-body-size':`${settings.text.body}px`,'--lab-interface-size':`${settings.text.interface}px`,'--lab-market-size':`${settings.text.market}px`
    };
    for(const mode of ['light','dark'] as const)for(const [key,value] of Object.entries(settings.colors[mode]))vars[`--lab-${mode}-${key}`]=value;
    for(const mode of ['light','dark'] as const)for(const [surface,value] of Object.entries(settings.colors.gradients[mode]))vars[`--lab-${mode}-gradient-${surface}`]=value.enabled?gradientCss(value):'none';
    for(const [surface,value] of Object.entries(settings.colors.gradients[colorMode]))vars[`--lab-gradient-${surface}`]=value.enabled?gradientCss(value):'none';
    for(const [key,value]of Object.entries(settings.colors.resilience))vars[`--lab-rs-${key}`]=value;
    for(const [key,value]of Object.entries(vars))root.style.setProperty(key,value);
    for(const selector of ['.morning-sections > .panel','.benchmark-grid > .benchmark-card','.work-grid .panel'])Array.from(document.querySelectorAll<HTMLElement>(selector)).forEach((card,index)=>card.style.setProperty('--card-reveal-delay',`${Math.min(index,3)*settings.motion.cardStagger}ms`));
  },[settings,reduced,colorMode]);
  useEffect(()=>()=>{const root=document.documentElement;delete root.dataset.devLab;delete root.dataset.devReducedMotion;for(const key of Array.from(root.style))if(key.startsWith('--lab-'))root.style.removeProperty(key);},[]);
  const update=<K extends keyof Settings>(key:K,patch:Partial<Settings[K]>)=>setSettings(old=>({...old,[key]:{...old[key],...patch}}));
  const palette=settings.colors[colorMode];
  const updateGradient=(surface:keyof GradientSurfaces,patch:Partial<Gradient>|Gradient)=>setSettings(old=>({...old,colors:{...old.colors,gradients:{...old.colors.gradients,[colorMode]:{...old.colors.gradients[colorMode],[surface]:{...old.colors.gradients[colorMode][surface],...patch}}}}}));
  const replay=(selector:string,duration:number,distance:number)=>{const node=document.querySelector<HTMLElement>(selector);if(!node)return;node.scrollIntoView({behavior:'smooth',block:'center'});window.setTimeout(()=>{node.animate([{opacity:0,transform:`translateY(${distance}px)`},{opacity:1,transform:'translateY(0)'}],{duration,easing:'cubic-bezier(.18,.72,.24,1)'});},220);};
  const replaySpectrum=()=>{const bars=Array.from(document.querySelectorAll<HTMLElement>('.distribution-bar>span'));bars[0]?.scrollIntoView({behavior:'smooth',block:'center'});window.setTimeout(()=>bars.forEach((bar,index)=>bar.animate([{transform:'scaleX(0)'},{transform:'scaleX(1)'}],{duration:settings.motion.resilienceMs,delay:index*settings.motion.resilienceStagger,easing:'cubic-bezier(.18,.72,.24,1)'})),220);};
  const copy=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(settings,null,2));setCopied(true);window.setTimeout(()=>setCopied(false),1800);}catch{setCopied(false);}};
  const resetAll=()=>{setSettings(structuredClone(defaults));setReduced(false);};
  const modeLabel=useMemo(()=>colorMode==='light'?'Light mode':'Dark mode',[colorMode]);
  return <aside className={`design-lab ${open?'is-open':''}`} aria-label="Dashboard design labs">
    <button className="design-lab-trigger" onClick={()=>setOpen(v=>!v)} aria-expanded={open}><SlidersHorizontal size={17}/><span>Design lab</span>{open?<X size={16}/>:<span className="lab-dev-tag">DEV</span>}</button>
    {open&&<div className="design-lab-panel">
      <div className="lab-heading"><div><strong>Fine tune the dashboard</strong><small>Changes preview live and save in this browser.</small></div><button aria-label="Close design lab" onClick={()=>setOpen(false)}><X size={17}/></button></div>
      <div className="lab-tabs" role="tablist">{(['motion','text','color'] as const).map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='color'?'Color':t[0].toUpperCase()+t.slice(1)}</button>)}</div>
      {tab==='motion'&&<div className="lab-body">
        <Group title="Section headers" defaultOpen><Range label="Fade and slide" value={settings.motion.headingMs} defaultValue={defaults.motion.headingMs} min={100} max={1800} step={10} unit=" ms" onChange={v=>update('motion',{headingMs:v})}/><Range label="Slide distance" value={settings.motion.headingY} defaultValue={defaults.motion.headingY} min={0} max={40} unit=" px" onChange={v=>update('motion',{headingY:v})}/><button className="lab-action" onClick={()=>replay('.morning-section .section-heading-row',settings.motion.headingMs,settings.motion.headingY)}><Play size={13}/>Replay heading</button></Group>
        <Group title="Morning paper"><Range label="Settle duration" value={settings.motion.paperMs} defaultValue={defaults.motion.paperMs} min={100} max={1800} step={10} unit=" ms" onChange={v=>update('motion',{paperMs:v})}/><Range label="Slide distance" value={settings.motion.paperY} defaultValue={defaults.motion.paperY} min={0} max={40} unit=" px" onChange={v=>update('motion',{paperY:v})}/><Range label="Metadata delay" value={settings.motion.paperDelay} defaultValue={defaults.motion.paperDelay} min={0} max={1200} step={10} unit=" ms" onChange={v=>update('motion',{paperDelay:v})}/><button className="lab-action" onClick={()=>replay('.morning-section .paper-kicker',settings.motion.paperMs,settings.motion.paperY)}><Play size={13}/>Replay paper</button></Group>
        <Group title="Jump to scanner"><Range label="Cue duration" value={settings.motion.jumpMs} defaultValue={defaults.motion.jumpMs} min={100} max={1800} step={10} unit=" ms" onChange={v=>update('motion',{jumpMs:v})}/><Range label="Cue delay" value={settings.motion.jumpDelay} defaultValue={defaults.motion.jumpDelay} min={0} max={1600} step={10} unit=" ms" onChange={v=>update('motion',{jumpDelay:v})}/><Range label="Bounce distance" value={settings.motion.jumpY} defaultValue={defaults.motion.jumpY} min={0} max={18} unit=" px" onChange={v=>update('motion',{jumpY:v})}/><button className="lab-action" onClick={()=>replay('.morning-section .section-jump',settings.motion.jumpMs,settings.motion.jumpY)}><Play size={13}/>Replay jump cue</button></Group>
        <Group title="Cards"><Range label="Settle duration" value={settings.motion.cardMs} defaultValue={defaults.motion.cardMs} min={100} max={1800} step={10} unit=" ms" onChange={v=>update('motion',{cardMs:v})}/><Range label="Slide distance" value={settings.motion.cardY} defaultValue={defaults.motion.cardY} min={0} max={40} unit=" px" onChange={v=>update('motion',{cardY:v})}/><Range label="Stagger" value={settings.motion.cardStagger} defaultValue={defaults.motion.cardStagger} min={0} max={400} step={5} unit=" ms" onChange={v=>update('motion',{cardStagger:v})}/><button className="lab-action" onClick={()=>replay('.morning-sections > .panel',settings.motion.cardMs,settings.motion.cardY)}><Play size={13}/>Replay a card</button></Group>
        <Group title="Resilience bars"><Range label="Fill duration" value={settings.motion.resilienceMs} defaultValue={defaults.motion.resilienceMs} min={100} max={1800} step={10} unit=" ms" onChange={v=>update('motion',{resilienceMs:v})}/><Range label="Segment stagger" value={settings.motion.resilienceStagger} defaultValue={defaults.motion.resilienceStagger} min={0} max={500} step={5} unit=" ms" onChange={v=>update('motion',{resilienceStagger:v})}/><button className="lab-action" onClick={replaySpectrum}><Play size={13}/>Replay spectrum</button></Group>
        <Group title="Sources card"><Range label="Open / close duration" value={settings.motion.sourcesMs} defaultValue={defaults.motion.sourcesMs} min={100} max={1400} step={10} unit=" ms" onChange={v=>update('motion',{sourcesMs:v})}/><button className="lab-action" onClick={()=>{const summary=document.querySelector<HTMLElement>('.sources-summary');summary?.scrollIntoView({behavior:'smooth',block:'center'});window.setTimeout(()=>summary?.click(),220);}}><Play size={13}/>Toggle Sources card</button></Group>
        <div className="lab-check-row"><label className="lab-check"><input type="checkbox" checked={reduced} onChange={e=>setReduced(e.target.checked)}/> Preview reduced motion</label><button type="button" className="lab-reset" aria-label="Reset reduced motion preview to default" title="Reset reduced motion preview to default" onClick={()=>setReduced(false)}><RotateCcw size={13}/></button></div>
      </div>}
      {tab==='text'&&<div className="lab-body"><p className="lab-intro">Adjust the live type hierarchy. Page headings keep separate desktop and mobile values.</p>
        <Group title="Headings" defaultOpen><Range label="Page title · desktop" value={settings.text.titleDesktop} defaultValue={defaults.text.titleDesktop} min={24} max={64} unit=" px" onChange={v=>update('text',{titleDesktop:v})}/><Range label="Page title · mobile" value={settings.text.titleMobile} defaultValue={defaults.text.titleMobile} min={22} max={48} unit=" px" onChange={v=>update('text',{titleMobile:v})}/><Range label="Section headings" value={settings.text.section} defaultValue={defaults.text.section} min={16} max={40} unit=" px" onChange={v=>update('text',{section:v})}/><Range label="Card headings" value={settings.text.card} defaultValue={defaults.text.card} min={12} max={28} unit=" px" onChange={v=>update('text',{card:v})}/></Group>
        <Group title="Body and data" defaultOpen><Range label="Brief text" value={settings.text.body} defaultValue={defaults.text.body} min={11} max={22} unit=" px" onChange={v=>update('text',{body:v})}/><Range label="General interface" value={settings.text.interface} defaultValue={defaults.text.interface} min={12} max={22} unit=" px" onChange={v=>update('text',{interface:v})}/><Range label="Market numbers" value={settings.text.market} defaultValue={defaults.text.market} min={20} max={56} unit=" px" onChange={v=>update('text',{market:v})}/></Group>
        <div className="lab-type-preview"><span>Morning Brief · Relative strength</span><strong>Premarket snapshot</strong><p>Body copy preview · Overnight moves, levels, events, and notes.</p><b className="mono">5,812.25 <i>+0.24%</i></b></div>
      </div>}
      {tab==='color'&&<div className="lab-body"><p className="lab-intro">Editing {modeLabel.toLowerCase()} colors to match the page theme. Resilience colors apply in both modes.</p>
        <Group title={`${modeLabel} · surfaces and text`} defaultOpen>{([['background','Page background'],['marketStrip','Market context background'],['surface','Card surface'],['secondary','Secondary surface'],['foreground','Body text'],['header','Header text'],['secondaryText','Secondary text'],['border','Outer border'],['divider','Inner divider'],['up','Price up'],['down','Price down']] as const).map(([key,label])=><Color key={key} label={label} value={palette[key]} defaultValue={defaults.colors[colorMode][key]} onChange={v=>update('colors',{[colorMode]:{...palette,[key]:v}})}/>)}</Group>
        <Group title="Surface gradients · active theme" defaultOpen>{([['background','Page background'],['marketStrip','Market context'],['surface','Card surfaces'],['secondary','Secondary surfaces']] as const).map(([key,label])=><GradientControl key={key} label={label} value={settings.colors.gradients[colorMode][key]} defaultValue={defaults.colors.gradients[colorMode][key]} onChange={patch=>updateGradient(key,patch)}/>)}</Group>
        <Group title="Resilience spectrum · shared across themes" defaultOpen>{([['exceptional','Exceptional RS'],['clear','Clear RS'],['moderate','Moderate RS'],['market','Market-like'],['laggard','Laggard']] as const).map(([key,label])=><Color key={key} label={label} value={settings.colors.resilience[key]} defaultValue={defaults.colors.resilience[key]} onChange={v=>update('colors',{resilience:{...settings.colors.resilience,[key]:v}})}/>)}</Group>
        <div className="lab-palette-preview"><span style={{background:palette.background,color:palette.foreground}}>Body</span><span style={{background:palette.surface,color:palette.header,borderColor:palette.border}}>Header</span><span style={{background:palette.secondary,color:palette.secondaryText}}>Secondary</span><span style={{color:palette.up}}>+1.2%</span><span style={{color:palette.down}}>−0.8%</span></div>
      </div>}
      <div className="lab-footer"><button className="lab-action" onClick={resetAll}><RotateCcw size={14}/>Reset all to defaults</button><button className="lab-copy" onClick={copy}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'Copied':'Copy settings'}</button></div>
    </div>}
  </aside>;
}
